"""
test_sticker_sampler.py — offline tests for sticker sampling.
Uses synthetic images generated by tests/fixtures/__init__.py.
"""

from __future__ import annotations

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import numpy as np
import pytest

import config
from src.sticker_sampler import StickerSampler, _central_patch, _is_glare
from tests.fixtures import make_fixtures


@pytest.fixture(scope="module", autouse=True)
def fixtures():
    return make_fixtures()


@pytest.fixture()
def sampler() -> StickerSampler:
    return StickerSampler(
        warp_size=config.WARP_SIZE,
        patch_frac=config.PATCH_FRAC,
        glare_v_thresh=config.GLARE_V_THRESH,
        glare_s_thresh=config.GLARE_S_THRESH,
    )


def _uniform_image(bgr: tuple[int, int, int], size: int = 300) -> np.ndarray:
    img = np.zeros((size, size, 3), dtype=np.uint8)
    img[:] = bgr
    return img


def _mixed_image(colors: list[tuple[int, int, int]], size: int = 300) -> np.ndarray:
    assert len(colors) == 9
    img = np.zeros((size, size, 3), dtype=np.uint8)
    cell = size // 3
    for i, c in enumerate(colors):
        row, col = divmod(i, 3)
        y, x = row * cell, col * cell
        h = cell if row < 2 else size - y
        w = cell if col < 2 else size - x
        img[y : y + h, x : x + w] = c
    return img


class TestCentralPatch:
    def test_returns_inner_rect(self):
        px, py, pw, ph = _central_patch(0, 0, 100, 100, 0.5)
        assert pw == 50
        assert ph == 50
        assert px == 25
        assert py == 25

    def test_at_least_one_pixel(self):
        px, py, pw, ph = _central_patch(0, 0, 1, 1, 0.1)
        assert pw >= 1
        assert ph >= 1


class TestIsGlare:
    def test_pure_white_is_glare(self):
        import numpy as np
        white = np.full((20, 20, 3), 255, dtype=np.uint8)
        assert _is_glare(white, v_thresh=0.92, s_thresh=0.08)

    def test_saturated_colour_is_not_glare(self):
        blue = np.zeros((20, 20, 3), dtype=np.uint8)
        blue[:, :, 0] = 200  # strong blue
        assert not _is_glare(blue, v_thresh=0.92, s_thresh=0.08)


class TestStickerSampler:
    def test_returns_nine_samples(self, sampler):
        img = _uniform_image((0, 200, 0))
        samples = sampler.sample(img)
        assert len(samples) == 9

    def test_indices_zero_to_eight(self, sampler):
        img = _uniform_image((100, 100, 100))
        samples = sampler.sample(img)
        assert [s.index for s in samples] == list(range(9))

    def test_uniform_face_all_same_colour(self, sampler):
        target = (0, 180, 0)
        img = _uniform_image(target)
        samples = sampler.sample(img)
        for s in samples:
            # Allow ±5 per channel due to integer arithmetic
            assert np.allclose(s.bgr, target, atol=5), (
                f"Sticker {s.index} colour {s.bgr.tolist()} != {target}"
            )

    def test_uniform_face_tight_spread(self, sampler):
        """A uniform face should have near-zero intra-face spread."""
        from src.color_classifier import LabClassifier, Palette
        import config

        img = _uniform_image((0, 0, 200))  # red
        samples = sampler.sample(img)
        palette = Palette(config.DEFAULT_PALETTE)
        clf = LabClassifier(palette, delta_e_max=config.DELTA_E_MAX)
        bgr_list = [s.bgr for s in samples]
        spread = clf.max_pairwise_delta_e(bgr_list)
        assert spread < config.INTRA_FACE_DELTA_E, (
            f"Uniform face spread {spread:.2f} ≥ threshold {config.INTRA_FACE_DELTA_E}"
        )

    def test_mixed_face_one_off_sticker(self, sampler):
        """Centre sticker (index 4) should be distinctly different from corners."""
        white = (255, 255, 255)
        blue  = (200, 50, 10)
        colours = [white] * 4 + [blue] + [white] * 4
        img = _mixed_image(colours)
        samples = sampler.sample(img)

        centre = samples[4].bgr
        corner = samples[0].bgr

        # Centre should be close to blue
        assert abs(int(centre[0]) - blue[0]) < 30, (
            f"Centre BGR {centre.tolist()} not close to blue {blue}"
        )
        # Corner should be close to white
        assert abs(int(corner[0]) - white[0]) < 30 and abs(int(corner[1]) - white[1]) < 30, (
            f"Corner BGR {corner.tolist()} not close to white {white}"
        )

    def test_cell_rects_cover_image(self, sampler):
        """All cell rects together should tile the full WARP_SIZE square."""
        img = _uniform_image((128, 128, 128))
        samples = sampler.sample(img)
        size = config.WARP_SIZE
        area = sum(s.cell_rect[2] * s.cell_rect[3] for s in samples)
        assert area == size * size, f"Cell rects don't tile: total area {area} != {size*size}"

    def test_no_uncertain_on_saturated_colour(self, sampler):
        """Deeply saturated colours should not be flagged as glare."""
        img = _uniform_image((200, 0, 0))  # pure blue
        samples = sampler.sample(img)
        assert all(not s.uncertain for s in samples)

    def test_uncertain_on_pure_white(self, sampler):
        """Pure white uniform face should flag all stickers as uncertain glare."""
        img = _uniform_image((255, 255, 255))
        samples = sampler.sample(img)
        assert all(s.uncertain for s in samples)
